const data = {
  items: [
    {
      id: 1,
      title: "Rolex Sea - Dweller",
      price: 37500000,
      image: require('./images/img1.png'),
      category: "Rolex",
      descripcion:"El bisel giratorio unidireccional graduado 60 minutos del Sea-Dweller permite visualizar los tiempos de inmersión y descompresión con total seguridad. Está equipado con un disco Cerachrom negro patentado y fabricado por Rolex en una cerámica prácticamente imposible de rayar o alterar por los rayos ultravioleta. La sobria esfera negra aloja grandes índices y agujas Chromalight, recubiertas de un material luminiscente de larga duración, que emite un color azul, para una excelente legibilidad en la oscuridad.",
      materiales: "Oyster, 43 mm, acero Oystersteel y oro amarillo.",
      cantidad: 1,
    },
    {
      id: 2,
      title: "Rolex 1908",
      price: 105640000,
      image: require('./images/img2.png'),
      category: "Rolex",
      descripcion:"El color, los reflejos, la textura de su superficie, así como los elementos que la decoran o incluso el diseño del conjunto, le confieren al reloj toda su personalidad. Se trata de una serie de gestos y operaciones que, desde los primeros esbozos hasta el control final, pasando por las etapas de coloración y colocación de los indicadores, requieren a profesionales especializados. Algunas de estas profesiones se remontan a los orígenes de la relojería.",
      materiales: "39 mm, oro amarillo de 18 quilates, acabado pulido.",
      cantidad: 1,
    },
    {
      id: 3,
      title: "Rolex Cosmograph Daytona",
      price: 93206000,
      image: require('./images/img3.png'),
      category: "Rolex",
      descripcion:"Este espectacular reloj incluye una escala taquimétrica, sus tres contadores y sus pulsadores. El bisel presenta una escala taquimétrica que permite leer la velocidad media en una distancia determinada en función del tiempo cronometrado. Esta escala ofrece una legibilidad óptima, lo que convierte el Cosmograph Daytona en el instrumento perfecto para medir la velocidad hasta las 400 unidades por hora, ya se trate de kilómetros o millas.",
      materiales: "Oyster, 40 mm, acero Oystersteel y oro amarillo.",
      cantidad: 1,
    },
    {
      id: 4,
      title: "Rolex Cosmograph Submarine",
      price: 70250000,
      image: require('./images/img4.png'),
      category: "Rolex",
      descripcion:"El bisel giratorio del Submariner es una característica fundamental de este reloj. Sus graduaciones de 60 minutos permiten controlar con seguridad y precisión el tiempo de inmersión y las paradas de descompresión. Manufacturado por Rolex a partir de una cerámica dura y resistente a la corrosión, el disco del bisel Cerachrom es prácticamente imposible de rayar.",
      materiales: "Oyster, 41 mm, acero Oystersteel y oro amarillo.",
      cantidad: 1,
    },
    {
      id: 5,
      title: "Rolex Datejust",
      price: 43100000,
      image: require('./images/img5.png'),
      category: "Rolex",
      descripcion:"La esfera es el rostro distintivo de un reloj Rolex, el mayor responsable de su identidad y legibilidad. Caracterizada por sus índices de oro que evitan la pérdida de brillo, cada esfera Rolex está diseñada y manufacturada en nuestros talleres, principalmente a mano, para garantizar su perfección.",
      materiales: "Oyster, 36 mm, acero Oystersteel y oro blanco.",
      cantidad: 1,
    },
    {
      id: 6,
      title: "Rolex Sky - Dweller",
      price: 92320000,
      image: require('./images/img6.png'),
      category: "Rolex",
      descripcion:"Un triángulo rojo fijo invertido en la esfera señala la hora de referencia, en el disco de 24 horas descentrado. De un solo vistazo, esta visualización de 24 horas distingue claramente las horas del día y las de la noche en el otro huso horario. Sus esferas pasan a estar dotadas de índices de las horas rectangulares y de agujas alargadas, así como de una visualización Chromalight con luminiscencia de larga duración, con el fin de mejorar más aún su legibilidad. Un rectángulo de color rojo oscuro en una de las 12 ventanas sobre la esfera indica el mes en curso. La fecha está conectada a la hora local y cambia automáticamente en función de la hora local del viajero.",
      materiales: "Oyster, 42 mm, acero Oystersteel y oro amarillo.",
      cantidad: 1,
    },
    {
      id: 7,
      title: "Rolex Day - Date",
      price: 98650000,
      image: require('./images/img7.png'),
      category: "Rolex",
      descripcion:"Esta esfera presenta índices en oro de 18 quilates engastados de 32 diamantes y números romanos VI y IX en oro de 18 quilates engastados de 24 diamantes, y está tallada en cornalina, una piedra anaranjada que se distingue por líneas de formas y grosores variables que componen una sutil escala cromática. La esfera es el rostro distintivo de un reloj Rolex, el mayor responsable de su identidad y legibilidad. Caracterizada por sus índices de oro que evitan la pérdida de brillo, cada esfera Rolex está diseñada y manufacturada en nuestros talleres, principalmente a mano, para garantizar su perfección.",
      materiales: "Oyster, 36 mm, oro amarillo y diamantes.",
      cantidad: 1,
    },
    {
      id: 8,
      title: "Rolex Oyster - Perpetual",
      price: 30620000,
      image: require('./images/img8.png'),
      category: "Rolex",
      descripcion:"Bautizado como «Celebration», este motivo inédito se propone para el Oyster Perpetual 31, el Oyster Perpetual 36 y el Oyster Perpetual 41. Compuesto por burbujas perfiladas en negro de diferentes tamaños, retoma los luminosos colores de la esferas lacadas presentadas en 2020: azul turquesa para el fondo y rosa candy, amarillo, rojo coral y verde para las burbujas.",
      materiales: "Oyster, 41 mm, acero Oystersteel",
      cantidad: 1,
    },
    {
      id: 9,
      title: "Rolex GMT - Master II",
      price: 78780000,
      image: require('./images/img9.png'),
      category: "Rolex",
      descripcion:"Este modelo presenta una esfera negra y un Disco de bisel Cerachrom bicolor en cerámica gris y negra bicolor. El GMT‑Master II dispone de una aguja adicional que da la vuelta a la esfera en 24 horas y complementa a las tradicionales agujas de las horas, minutos y segundos, así como de un bisel giratorio bidireccional graduado 24 horas. La aguja adicional de 24 horas, con su color distintivo, indica la hora de referencia, la del lugar de residencia, en un primer huso horario que se lee sobre la graduación del bisel.",
      materiales: "Oyster, 40 mm, acero Oystersteel y oro amarillo.",
      cantidad: 1,
    },
    {
      id: 10,
      title: "Rolex Lady - Datejust",
      price: 110900000,
      image: require('./images/img10.png'),
      category: "Rolex",
      descripcion:"Los engastadores, al igual que los escultores, modelan los metales preciosos para preparar el espacio donde alojarán perfectamente cada piedra preciosa de forma manual. Con el arte y «savoir‑faire» de los joyeros, cada piedra se alinea meticulosamente hasta engastarla de forma segura en el oro o en el platino. Además contribuyen a la belleza del engaste de piedras y su calidad, la alineación precisa del tamaño de las piedras, su orientación y posición, la regularidad, la solidez y las proporciones del engaste, así como el acabado del trabajo en metal.",
      materiales: "Oyster, 28 mm, oro Everose y diamantes",
      cantidad: 1,
    },
    {
      id: 11,
      title: "Rolex Explorer",
      price: 37050000,
      image: require('./images/img11.png'),
      category: "Rolex",
      descripcion:"La esfera es el rostro distintivo de un reloj Rolex, el mayor responsable de su identidad y legibilidad. Los números 3, 6 y 9, característicos del modelo Explorer, están rellenos de un material luminiscente, que emite un color azul de larga duración, igual que los índices y las agujas. Como todos los relojes Rolex, la esfera del Explorer 40 está diseñada y manufacturada en nuestros talleres, principalmente a mano, para garantizar su perfección.",
      materiales: "Oyster, 40 mm, acero Oystersteel",
      cantidad: 1,
    },
    {
      id: 12,
      title: "Rolex Yacht - Master",
      price: 67470000,
      image: require('./images/img12.png'),
      category: "Rolex",
      descripcion:"El bisel giratorio bidireccional graduado 60 minutos en relieve del Yacht‑Master está realizado íntegramente en metal precioso o dotado de un disco Cerachrom de cerámica de alta tecnología. Los números y graduaciones pulidos en relieve destacan claramente en el fondo mate pulido con chorro de arena. Este bisel funcional —que permite calcular, por ejemplo, el tiempo de navegación entre dos boyas— es además un componente clave de la distintiva identidad visual de este modelo.",
      materiales: "Oyster, 42 mm, titanio RLX",
      cantidad: 1,
    }
  ],
};

export default data;